export const FETCH_TRANSACTION_LIST = 'FETCH_TRANSACTION_LIST';
export const CHANGE_CURRENT_VIEW = 'CHANGE_CURRENT_VIEW';
export const CHANGE_ORDERS_PAGE = 'CHANGE_ORDERS_PAGE';
export const FETCH_BLACK_LIST = 'FETCH_BLACK_LIST';
export const REMOVE_BLACK_ONE = 'REMOVE_BLACK_ONE';
